import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/header/navbar";

const open = Open_Sans({
  weight: ["400", "600"],
  subsets: ["latin"],
  style: ["normal"],
  variable: "--font-open_sans",
});
const myFont = localFont({
  src: "../public/Siyamrupali.ttf",
  display: "swap",
  variable: "--font-siyamrupali",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${myFont.className}`}>
        <Navbar />
        <div className="bg">
          <div className="max-w-7xl mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
